### PR TITLE
Implement consistent row addressing by Excel row number starting with 1

### PR DESCRIPTION
**Pull request by albenik**
# PR Details

Implement consistent row addressing by Excel row number starting with 1

## Description

1. Added second versions for all row manipulation methods with zero-based row addressing.
2. Fixed methods documentation to explicitly describe which row addressing used in method.
3. Added WARNING to README.md.
4. Cosmetic change: All row test moved to file `rows_test.go`.

## Related Issue

https://github.com/360EntSecGroup-Skylar/excelize/issues/349

## Motivation and Context

Yet another entropy fix :)
I spent a much time to find bugs is my program related to different row numbering logic with different methods.

## How Has This Been Tested

Unit tests has been updated and succeed.

## Types of changes

- [x] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by xuri** [comment]
Hi @albenik, thanks for your PR. I recommend changing the existing functions instead of add new series functions, then releasing the new version prompting upgrade API compatibility  for the existing user, eliminating two different line number indexes.

**Comment by albenik** [comment]
Hi @xuri.

By guidelines (https://semver.org/ & https://github.com/golang/go/wiki/Modules#semantic-import-versioning), after incompatible API changes, it's necessary to update version to `v2.0.0` and module import path to `github.com/360EntSecGroup-Skylar/excelize/v2`.

And also remove TravisCI tests from older go versions which not supports go modules.

Do you plan to follow guidelines? Or I should simply break compatibility with README note?

**Comment by xuri** [comment]
This change will be included in the next version 1.5.0. I suggest simply break compatibility and place a README notes.

**Comment by albenik** [comment]
@xuri done

**Pull request merged**
