### PR TITLE
Added helper functions to set the chart size.

### PR DESCRIPTION
**Pull request by jdevelop**
Just a nice addition to set the chart size upon inserting. 

It's rather too small and insignificant to create an enhancement issue for it first.

### CODE REVIEW

**Comment by xuri** [comment]
Thanks for your job. I think the size parameter should be in the style string, it is not recommended to add parameters for the `AddChart()` function.

**Comment by xuri** [comment]
Size attributes are part of the style, the chart also contains many other attributes. If strip out the size parameters from the style parameters will bring a sense of split.

**Comment by jdevelop** [comment]
Sounds like a good thing to have. Do you mind sharing which properties we can extract from the current style and use in the new way? I assume that it implies renaming of `chartOptions` in sort of `chartStyle` and providing more properties that could be extracted from the style itself.

**Comment by jdevelop** [comment]
Moved the chart dimension into the format string, pls take a look.

**Comment by xuri** [comment]
Thank you. Actually, I am considering to make style structs public, reference issue #203.

**Pull request merged**
