### PR TITLE
fix calc object position  for addPicture

### PR DESCRIPTION
**Pull request by yoshhiide**
# PR Details

Fix calc object position for addPicture.

## Description

The target cell for calclator the width and height 

## Motivation and Context

I wanted to fix one of the factors that caused the size of the inserted image to be incorrect.

## How Has This Been Tested

Verified by local excel()

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by yoshhiide** [comment]
It is an image before this PR
logic_image

**Comment by xuri** [comment]
Hi @yoshhiide, thanks for you PR. I tested the size of the inserted image base on the version [eca6618](https://github.com/360EntSecGroup-Skylar/excelize/tree/eca66180f191ba1209e5d50859be51eec7954281) and it seems works well. Could you provide the code to reproduce the problem?

**Comment by yoshhiide** [comment]
You can try it with this code and files.
https://gist.github.com/yoshhiide/d1bf0ed27b33629552d52b82a284b464

image1
[input_change_x.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3052645/input_change_x.xlsx)
[input_change_y.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3052646/input_change_y.xlsx)
[input_def.xlsx](https://github.com/360EntSecGroup-Skylar/excelize/files/3052647/input_def.xlsx)

**Comment by yoshhiide** [comment]
There is no problem if the width and height of the cell before and after the inserted cell are the same, but it will be a problem if they are different.

**Comment by xuri** [comment]
LGTM, thanks @yoshhiide.

**Pull request merged**
